### ISSUE TITLE
Wifi driver for joystick

### ISSUE THREAD

**Issue by mkeyno** [phanikmr/RacePad#1]
hi , sorry to open a ticket for my question, but I have some questions that your probably advise is really appreciated
Actually I've been trying to send some game keys, base on HID protocol to the computer by wifi link(ESP8266). PC computer with OS like Microsoft Windows instantly make "HID-compliant game controller" driver with typical USB joystick , my question is, how make specific driver which is shows up same as "HID-compliant game controller" but listen to specific IP address instead of USB
tnx

**Comment by phanikmr** [comment]
Hi, Sorry I don't have any experience about writing drivers this particular application RacePad is just simulator of key codes on client-server architecture but I can suggest you go through this https://github.com/x360ce/x360ce which is an actual emulator for PC to emulate Xbox 360 controller.
https://www.osr.com/getting-started-writing-windows-drivers/
